-- 코드를 작성해주세요
SELECT r.ITEM_ID, r.ITEM_NAME, r.RARITY
FROM ITEM_INFO i JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO r ON t.ITEM_ID = r.ITEM_ID AND i.RARITY = 'RARE'
ORDER BY r.ITEM_ID DESC